import { ReactNode } from "react";
import Head from "next/head";
import { Header } from "./header";
import { Footer } from "./footer";
import { Container } from "react-bootstrap";

type IProps = {
    children: ReactNode;
}
export default function Site(props: IProps) {
    return (
        <>
            <Head>
                <meta charSet="utf-8" />
                <title>Kino teatras</title>
                <meta name="description" content="Generated by create nxt app" />
                <meta name="viewport" content="width=device-width, initial-scaele=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container fluid="md">
                <Header />
                <main>{props.children}</main>
                <Footer />
            </Container>
        </>
    );
}
